### ISSUE TITLE
logprob values

### ISSUE THREAD

**Issue by grburgess** [minaskar/zeus#1]
Hello,

I cannot tell from the documentation if the log prob or log likelihood values are stored. Can you point me to this?

**Comment by minaskar** [comment]
Hi Michael,

The log prob values are not stored in the current (1.0.3) release of zeus, just the chain samples. However, this is something that will be added in a future release, probably in 1.0.4 next week.

**Comment by grburgess** [comment]
Thanks! We store them in our software and wanted to add zeus into our sampler suite, but right now it means revaluate the whole chain :) 

looking forward to that.

**Comment by minaskar** [comment]
May ask if your software package is/will be public. I'm interested to see how people use zeus.

I'll update this thread when the feature is added to zeus (probably a matter of days).

**Comment by grburgess** [comment]
Absolutely:
https://threeml.readthedocs.io/en/latest/notebooks/Bayesian_tutorial.html

https://threeml.readthedocs.io/en/latest/index.html

It is a multi-messenger spectral/spatial fitting software package for astrophysics. I'm currently rewriting the Bayes API to make it easier to switch between the samplers and add them on.

**Comment by minaskar** [comment]
Hi Michael, please have a look at the latest version (1.0.5).

Let me know if that solves your issue.

Minas

**Comment by grburgess** [comment]
I think this got it. Thanks!

**Comment by grburgess** [comment]
And we have implemented it here:
https://threeml.readthedocs.io/en/latest/notebooks/Bayesian_tutorial.html#The-Zeus-sampler

We cannot have it yet as a default sampler because it is not on conda which we use to build all of our dependencies due to having many, but when it is on conda, we will pop that right in. Thanks for this!
