### ISSUE TITLE
get_last_sample should be function

### ISSUE THREAD

**Issue by jeremysanders** [minaskar/zeus#10]
This is a minor issue, as I can work around the difference using `get_chain` instead.

In emcee, `get_last_sample` is a function which returns the last sample. In zeus this is a property. For compatibility, it would be useful to match the emcee API. It also doesn't make sense to me to use a property called get_XXX.

PS Thanks for working on this software and algorithm - initial tests are looking good

**Comment by minaskar** [comment]
Hi Jeremy,
Thanks a lot for spotting this! 
I'll make sure. it's fixed in the next release.

**Comment by minaskar** [comment]
This is done in version 2.2.2.

**Comment by jeremysanders** [comment]
Thanks very much!
