### ISSUE TITLE
Resuming a chain more efficiently

### ISSUE THREAD

**Issue by joezuntz** [minaskar/zeus#12]
Currently I think that if you resume a chain (by passing the result of `get_last_sample` to a new call to `run_mcmc`) then time is wasted recomputing the posteriors of the starting points, which were already computed last time.

Emcee lets you optionally pass in the posteriors of the starting point, if they are known.   Would this be possible for zeus?

**Comment by minaskar** [comment]
Hi @joezuntz,

You're absolutely right, I'll add this feature the next few days!

Thanks for spotting this!

**Comment by minaskar** [comment]
I've included this feature in the new version of zeus (2.2.2). Let me know if this is you meant.

**Comment by joezuntz** [comment]
That's perfect, thanks so much!
