### ISSUE TITLE
Can I resume jobs with the same Zeus sampler?

### ISSUE THREAD

**Issue by Jammy2211** [minaskar/zeus#14]
I am looking to make it so that I can cancel a Python script mid-run and then resume the job. With Emcee, I do this via the backend feature. 

I want to have access to all the previous chains and samples so that I can use previously computed autocorrelation times, and whatnot. So simply passing the previous chains to a new instance of the sampler doesn't quite cut it.

Does Zeus have a specific feature that support resuming jobs? If not, no problem, I can achieve the desired effect via pickling the EnsembleSampler (I hope!). couldn't find anything in the docs, but figured I'd ask before writing code to do this.

**Comment by minaskar** [comment]
If you mean to cancel the script using keyboard interrupt then this feature that you described is not supported (yet).

However, there're probably ways to what you want e.g. using the sample method or pickling the sampler as you mentioned.

**Comment by Jammy2211** [comment]
Got pickling working thanks, but I look forward to h5py support!
