### ISSUE TITLE
Print parameter values if likelihood fails

### ISSUE THREAD

**Issue by seshnadathur** [minaskar/zeus#19]
I am working with a problem where some points in parameter space give invalid inputs for which my likelihood fails. When this happens, I would like `zeus` to print the parameter values at the point that caused the failure (as is done by `emcee`) to make it easier to debug/understand the physical reason for the likelihood failure.

Can you implement this please?

**Comment by minaskar** [comment]
What exact value does your log-likelihood return when evaluated in one such point? Is it np.nan?

**Comment by seshnadathur** [comment]
I'm not sure: as I couldn't find the parameter values at which the failure occurred it is not so simple to reproduce it. If I come across it again I will check and let you know. Does it affect the fix you would need to implement?

**Comment by seshnadathur** [comment]
I should add that the running a chain with the exact same likelihood using `emcee` I hit a (probably similar) failure point, and `emcee` spat out the parameter values at that point. This was useful for me to code a workaround in the likelihood (which also now means that failure doesn't recur, so it's less easy to answer your question).

**Comment by minaskar** [comment]
I think I know what you mean. It's not when the likelihood returns an invalid value (e.g. np.nan) but when the likelihood raises an exception.

Could you confirm that the error message emcee provided looked like this?

```
emcee: Exception while calling your likelihood function:
  params: [-2.85976993  5.04287664]
  args: []
  kwargs: {}
  exception:
```

**Comment by seshnadathur** [comment]
Yes, that's right. Sorry about the confusing wording earlier!

**Comment by minaskar** [comment]
No worries. I'l implement it during the next few days.

**Comment by minaskar** [comment]
Sorry for the delay. Let me know if the feature works.
