### ISSUE TITLE
pip version does not have EnsembleSampler

### ISSUE THREAD

**Issue by AdityaSavara** [minaskar/zeus#6]
I used a pip install. Then tried to follow the example here:
https://zeus-mcmc.readthedocs.io/en/latest/

It didn't work. But changing EnsembleSampler to sampler worked.

**Comment by minaskar** [comment]
Thank you for raising this issue with us.

I'm in the process of updating the docs for some new features that I'll release in the next couple of days. Keep an eye for the new ``Moves Interface``. In the meantime, the sampler class should work with no issues.

All the best,
Minas

**Comment by AdityaSavara** [comment]
Great. One thing to note is that threeML is also using the variable name "sampler" : https://github.com/threeML/threeML/blob/master/threeML/bayesian/zeus_sampler.py

You may want to consider simply having sampler = EnxembleSampler in your code to maintain backwards compabitibility.

**Comment by minaskar** [comment]
I will do that! Thank you very much!
